import {useRef,useState} from 'react';
import {Bar,BarChart,CartesianGrid,Cell,LabelList,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {calls,quarter} from '@/lib/beauty';
import frequency from '@/data/call-frequency.json';

type Metric='literal'|'related'|'general';
type Term={term:string;category:string;count:number;prepared:number;qna:number;unknown:number};
type Doc={id:string;company:string;date:string;title:string;type:string;source:string;url?:string;status:string;callId?:number;wordCount?:number;counts?:{direct:number;brands:number;general:number};terms?:Term[];reason?:string;moments?:{term:string;category:string;count:number;section:string;seconds:number|null;line:number}[]};
const documents=frequency.documents as Doc[];
const quarters=Array.from({length:11},(_,i)=>`${i%4+1}Q${24+Math.floor(i/4)}`);
const metricNames={literal:'K-beauty만',related:'관련 표현 + 한국 브랜드',general:'일반 뷰티 표현'};
const categoryNames:Record<string,string>={direct:'K뷰티 직접 표현',brands:'한국 브랜드',general:'일반 뷰티'};
function value(d:Doc,metric:Metric){if(d.status!=='complete')return null;return metric==='literal'?(d.terms?.find(t=>t.term==='K-beauty')?.count||0):metric==='related'?(d.counts!.direct+d.counts!.brands):d.counts!.general}
function matches(t:Term,metric:Metric){return metric==='literal'?t.term==='K-beauty':metric==='related'?t.category!=='general':t.category==='general'}
function dateLabel(d:string){return `${d.slice(2,4)}.${d.slice(5,7)}${d.length>7?'.'+d.slice(8,10):''}`}
function Filter({label,options,value:current,onChange}:{label:string;options:{value:string;label:string}[];value:string;onChange:(v:any)=>void}){return <div className="calls-choices" role="group" aria-label={label}>{options.map(o=><button key={o.value} aria-pressed={current===o.value} onClick={()=>onChange(o.value)}>{o.label}</button>)}</div>}
export default function CallFrequency({onOpenNotes}:{onOpenNotes:(company:string)=>void}){
 const [company,setCompany]=useState('Ulta Beauty'),[metric,setMetric]=useState<Metric>('literal'),[eventType,setEventType]=useState('all'),[normalized,setNormalized]=useState(false),[selectedId,setSelectedId]=useState<string|null>(null);
 const chartRef=useRef<HTMLElement>(null);
 const selectedCompany=calls.companies.find((c:any)=>c.name===company)!;
 const filtered=documents.filter(d=>eventType==='all'||d.type===eventType);
 const docs=filtered.filter(d=>d.company===company).sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id));
 const complete=docs.filter(d=>d.status==='complete');
 const latest=docs.at(-1),latestComplete=complete.at(-1);
 const prior=latestComplete?complete.filter(d=>d.id!==latestComplete.id&&d.type===latestComplete.type).at(-1):undefined;
 const first=complete.find(d=>(value(d,metric)||0)>0);
 const detail=docs.find(d=>d.id===selectedId)||latestComplete;
 const chart=docs.map(d=>({...d,key:d.id,label:dateLabel(d.date),count:value(d,metric),amount:d.status==='complete'?(normalized?Number(((value(d,metric)||0)/Math.max(d.wordCount||0,1)*10000).toFixed(1)):value(d,metric)):null}));
 const knownAll=documents.filter(d=>d.status==='complete').length;
 const changeCompany=(name:string,scroll=false)=>{setCompany(name);setSelectedId(null);if(scroll)requestAnimationFrame(()=>chartRef.current?.scrollIntoView({behavior:'smooth',block:'start'}))};
 const terms=detail?.terms?.filter(t=>matches(t,metric))||[];
 const sectionSum=(part:'prepared'|'qna'|'unknown')=>terms.reduce((s,t)=>s+t[part],0);
 return <div className="calls-view frequency-view">
  <div className="frequency-intro"><b>같은 원문에서 세 번 말하면 3회.</b><span>요약 건수가 아닌 영문 전사본의 실제 표현 등장 횟수입니다. 경영진 발언과 질문을 모두 포함합니다.</span></div>
  <div className="calls-toolbar"><Filter label="집계 표현" value={metric} onChange={setMetric} options={Object.entries(metricNames).map(([value,label])=>({value,label}))}/><Filter label="자료 유형" value={eventType} onChange={setEventType} options={[{value:'all',label:'전체 자료'},{value:'earnings',label:'실적발표'},{value:'conference',label:'컨퍼런스·IR'}]}/></div>
  <section className="calls-matrix-panel" aria-label="실제 표현 횟수 비교">
   <div className="calls-matrix-heading"><div><h3>회사별 · 분기별 실제 등장 횟수</h3><p>{metricNames[metric]} · 숫자는 확보한 원문의 합계 · 회사 선택 시 자료별 추이</p></div><span>원문 {knownAll}개 집계</span></div>
   <div className="calls-matrix-scroll"><table className="calls-matrix"><thead><tr><th scope="col">회사</th>{quarters.map((q,i)=><th key={q} scope="col" className={i===quarters.length-1?'latest-quarter':undefined}>{q}</th>)}<th scope="col">합계</th><th scope="col">원문</th></tr></thead><tbody>{calls.companies.map((c:any)=>{
    const all=filtered.filter(d=>d.company===c.name),done=all.filter(d=>d.status==='complete'),partial=done.length<all.length||c.source!=='DB';
    return <tr key={c.name} className={company===c.name?'is-selected':''} tabIndex={0} aria-label={`${c.ko} 실제 횟수 추이`} onClick={()=>changeCompany(c.name,true)} onKeyDown={e=>{if(e.target===e.currentTarget&&(e.key==='Enter'||e.key===' ')){e.preventDefault();changeCompany(c.name,true)}}}><th scope="row"><button aria-pressed={company===c.name} onClick={e=>{e.stopPropagation();changeCompany(c.name,true)}}><i className={c.type==='브랜드'?'brand-dot':'retail-dot'}/><strong>{c.ko}</strong><span>{c.ticker}</span></button></th>{quarters.map((q,j)=>{const group=all.filter(d=>quarter(d.date)===q),ok=group.filter(d=>d.status==='complete'),sum=ok.reduce((s,d)=>s+(value(d,metric)||0),0),incomplete=ok.length<group.length||c.source!=='DB';return <td key={q} className={`${sum?'intensity-'+(sum>=10?3:sum>=3?2:1):''} ${j===quarters.length-1?'latest-quarter':''}`} title={ok.length?`${ok.length}개 원문 집계${incomplete?' · 일부 자료만 확보':''}`:'집계한 원문 없음'}>{ok.length?<>{sum}{incomplete&&<sup>*</sup>}</>:<span>—</span>}</td>})}<td className="total">{done.length?done.reduce((s,d)=>s+(value(d,metric)||0),0):'—'}{done.length>0&&partial&&<sup>*</sup>}</td><td className="checked-calls">{done.length}/{all.length||'?'}</td></tr>
   })}</tbody></table></div>
   <div className="calls-matrix-key"><span className="heat-key"><i/>1–2회 <i/>3–9회 <i/>10회+</span><span>0 = 확보 원문에서 0회 · — = 미집계 · * = 일부 자료의 합계</span></div>
   <p className="frequency-coverage">시험 집계: 울타뷰티는 조회 목록의 실적발표·컨퍼런스 전사본을 전부 집계했습니다. 다른 기업은 확보한 자료만 포함합니다. 유럽은 기존 코멘트의 선별 자료 기준이므로 기업 간 총횟수를 그대로 비교하지 마세요.</p>
  </section>
  <section className="panel frequency-chart-panel" ref={chartRef} aria-label="자료별 언급 강도">
   <div className="panel-head"><div><h3>{selectedCompany.ko} · 자료별 등장 횟수</h3><div className="panel-note">{metricNames[metric]} · {normalized?'원문 1만 단어당 횟수':'단위: 회'} · 최신 자료 노랑 강조</div></div><label className="frequency-company-label">기업<select aria-label="언급 추이 기업" value={company} onChange={e=>changeCompany(e.target.value)}>{calls.companies.map((c:any)=><option key={c.name} value={c.name}>{c.ko}</option>)}</select></label></div>
   <div className="stats three frequency-stats"><div className="stat"><div className="stat-label">최신 자료 · {latest?dateLabel(latest.date):'—'}</div><div className="stat-value">{latest?value(latest,metric)??'—':'—'}<small>회</small></div><div className="stat-note muted">{latest?.status==='complete'?latest.type==='earnings'?'실적발표':'컨퍼런스·IR':'원문 미집계'}</div></div><div className="stat"><div className="stat-label">직전 같은 유형 자료</div><div className="stat-value">{prior?value(prior,metric):'—'}<small>회</small></div><div className="stat-note muted">{prior?dateLabel(prior.date):'비교 자료 없음'}</div></div><div className="stat"><div className="stat-label">집계한 원문</div><div className="stat-value">{complete.length}<small>/ {docs.length}개</small></div><div className="stat-note muted">{first?`확보 자료 첫 등장 ${dateLabel(first.date)}`:'확보 자료에서 해당 표현 없음'}</div></div></div>
   <div className="frequency-measure"><Filter label="횟수 단위" value={normalized?'normalized':'count'} onChange={v=>setNormalized(v==='normalized')} options={[{value:'count',label:'실제 횟수'},{value:'normalized',label:'1만 단어당'}]}/><span className="muted">빈 막대 = 원문 미집계</span></div>
   {complete.length?<div className="frequency-chart-scroll"><div style={{minWidth:Math.max(860,docs.length*48),height:360}}><ResponsiveContainer width="100%" height="100%"><BarChart data={chart} margin={{top:36,right:24,bottom:12,left:0}}><CartesianGrid vertical={false} stroke="#2a3542"/><XAxis dataKey="key" tickFormatter={id=>chart.find(d=>d.id===id)?.label||''} interval={0} angle={-40} textAnchor="end" height={65} tick={{fill:'#8b98a5',fontSize:15}} axisLine={{stroke:'#2a3542'}} tickLine={false}/><YAxis allowDecimals={normalized} tick={{fill:'#8b98a5',fontSize:17}} axisLine={false} tickLine={false}/><Tooltip cursor={{fill:'#ffffff08'}} content={({active,payload}:any)=>{const d=payload?.[0]?.payload;return active&&d?<div className="chart-tip"><b>{d.label} · {d.type==='earnings'?'실적발표':'컨퍼런스·IR'}</b><p>{d.title}</p><p>실제 {d.count}회{normalized&&` · 1만 단어당 ${d.amount}회`}</p><p>원문 {(d.wordCount||0).toLocaleString()}단어</p></div>:null}}/><Bar dataKey="amount" minPointSize={3} maxBarSize={38} isAnimationActive={false}>{chart.map((d,i)=><Cell key={d.id} fill={i===chart.length-1?'#FFCB05':d.count===0?'#536170':'#5B9BD5'}/>)}<LabelList dataKey="amount" content={(p:any)=>p.value==null?null:<text x={Number(p.x)+Number(p.width)/2} y={Number(p.y)-10} textAnchor="middle" fill={p.fill==='#FFCB05'?'#FFCB05':p.value===0?'#8b98a5':'#fff'} fontSize={p.fill==='#FFCB05'?26:19} fontWeight={800}>{p.value}</text>}/></Bar></BarChart></ResponsiveContainer></div></div>:<div className="empty">이 기업은 아직 집계 가능한 원문을 확보하지 못했습니다.</div>}
   <p className="panel-foot">자료별 비교입니다. 긴 자료일수록 횟수가 늘 수 있으므로 ‘1만 단어당’도 함께 보세요. 반복 언급은 관심의 강도이며 긍정·부정 평가나 매출을 뜻하지는 않습니다.</p>
  </section>
  <section className="panel frequency-audit" aria-label="자료별 집계 근거"><div className="panel-head"><div><h3>원문별 숫자 확인</h3><p className="panel-note">자료 행을 누르면 단어별 집계 내역을 확인합니다. 최신순.</p></div><button className="link-button" onClick={()=>onOpenNotes(company)}>기존 컨콜 코멘트 보기 ↗</button></div><div className="table-wrap"><table><thead><tr><th>날짜</th><th>자료</th><th>K-beauty</th><th>관련 표현·브랜드</th><th>일반 뷰티</th><th>원문 단어</th></tr></thead><tbody>{[...docs].reverse().map(d=><tr key={d.id} className={detail?.id===d.id?'frequency-selected':''}><td><button className="frequency-doc-button" onClick={()=>setSelectedId(d.id)}>{dateLabel(d.date)}</button></td><td className="frequency-title-cell"><button className="frequency-doc-button" onClick={()=>setSelectedId(d.id)}>{d.title}</button><span>{d.type==='earnings'?'실적발표':'컨퍼런스·IR'} · {d.status==='complete'?'전체 원문 집계':'미집계'}</span></td><td>{value(d,'literal')??'—'}</td><td>{value(d,'related')??'—'}</td><td>{value(d,'general')??'—'}</td><td>{d.wordCount?.toLocaleString()??'—'}</td></tr>)}</tbody></table></div>
   {detail&&<div className="frequency-detail" aria-live="polite"><h4>{dateLabel(detail.date)} · {detail.title}</h4><p className="panel-note">{detail.source}{detail.callId&&` · 콜 ID ${detail.callId}`}{detail.url&&<> · <a href={detail.url} target="_blank" rel="noreferrer">원문 보기 ↗</a></>}</p>{detail.status==='complete'?<><div className="frequency-term-list">{terms.length?terms.map(t=><span key={t.term}><small>{categoryNames[t.category]}</small>{t.term}<b>{t.count}회</b></span>):<p>선택한 집계 기준에 해당하는 표현이 없습니다. 0회입니다.</p>}</div><p className="panel-note">선택 기준 합계 {value(detail,metric)}회 · 발표 본문 {sectionSum('prepared')}회 · Q&A {sectionSum('qna')}회 · 구간 구분 없음 {sectionSum('unknown')}회</p><p className="panel-note">Q&A에는 질문과 경영진의 답변이 모두 포함됩니다.</p>{metric!=='general'&&<details className="frequency-moments"><summary>원문 등장 시점 · 같은 문장의 반복도 각각 집계</summary><div>{detail.moments?.filter(m=>metric==='related'||m.term==='K-beauty').map((m,i)=><span key={i}>{m.seconds!=null?`${Math.floor(m.seconds/60)}:${String(Math.floor(m.seconds%60)).padStart(2,'0')}`:`원문 ${m.line}행`} · {m.term} <b>× {m.count}</b></span>)}</div></details>}</>:<p>{detail.reason||'전체 원문을 아직 집계하지 않았습니다.'} 0회로 해석하지 마세요.</p>}</div>}
  </section>
  <details className="frequency-method"><summary>집계 기준 · 포함 단어 · 자료 범위</summary><p><b>K-beauty만:</b> 대소문자와 하이픈·띄어쓰기 차이를 통일해 K-beauty / K beauty / Kbeauty의 실제 등장 횟수를 셉니다. 같은 발언에서 반복되면 각각 1회입니다.</p><p><b>관련 표현 + 한국 브랜드:</b> 직접 표현({frequency.directTerms.join(', ')})과 브랜드({frequency.brandTerms.join(', ')})의 합계입니다. 모든 한국 브랜드를 망라한 지표는 아닙니다.</p><p><b>일반 뷰티 표현:</b> beauty, skincare / skin care, cosmetics를 별도 집계합니다. Ulta Beauty·e.l.f. Beauty라는 회사명 및 직접 K뷰티 표현과 Beauty of Joseon은 이 항목에서 제외합니다. K뷰티 지표와 합산하지 않습니다.</p><p><b>범위:</b> 2024년 1월~2026년 9월, 자료 발표일 기준 분기입니다. 실적콜의 회계분기와 다를 수 있습니다. 미국·유니레버는 StockNow 조회 목록, 기타 유럽은 기존 코멘트의 출처 목록입니다. 월매출 업데이트·주주총회·슬라이드·공시 문서는 제외합니다.</p><p><b>원문:</b> StockNow는 자동전사이므로 브랜드명 오기·누락이 있을 수 있습니다. 웹 전사본은 제목·자동 요약을 제외하고 실제 전사 본문을 사용합니다. 미확보·부분 전사본은 횟수와 단어 수를 공개하지 않습니다. 1만 단어당 수치는 등장 횟수 ÷ 원문 단어 수 × 10,000입니다.</p><p>자료 확인 {frequency.updated} · 기존 코멘트 수 화면은 상단 버튼으로 언제든 전환할 수 있습니다.</p></details>
 </div>
}
